package com.example.cysafecampus.model;

import java.io.Serializable;

/**
 * Represents an event generated by a sensor.
 * Carries all context needed for AdminAgent to make decisions:
 * what happened, how severe, and where.
 */
public class SensorEvent implements Serializable {

    /** Type of event detected */
    private SensorEventType type;

    /**
     * Severity level from 1 (low) to 5 (critical).
     * Used by AdminAgent to decide whether to notify supervisors.
     */
    private int severity;

    /** The building element where the event was detected */
    private BuildingElement location;

    /** Timestamp of the event (simulation tick or system time) */
    private long timestamp;

    /**
     * Constructor for SensorEvent.
     * @param type the type of event
     * @param severity severity from 1 to 5
     * @param location the building element concerned
     */
    public SensorEvent(SensorEventType type, int severity, BuildingElement location) {
        this.type = type;
        this.severity = severity;
        this.location = location;
        this.timestamp = System.currentTimeMillis();
    }

    public SensorEventType getType() { return type; }
    public int getSeverity() { return severity; }
    public BuildingElement getLocation() { return location; }
    public long getTimestamp() { return timestamp; }

    @Override
    public String toString() {
        return "[" + type + " | severity=" + severity + " | location=" + location.getName() + "]";
    }
}
